### ISSUE TITLE
client.put does not throw AS_PROTO_RESULT_FAIL_BIN_NAME

### ISSUE THREAD

**Issue by rschmukler** [aerospike/aerospike-client-nodejs#114] opened 2016-02-22 21:24 UTC
If you put a record with a bin name length greater than 14 characters the client will just omit the bins on the record as opposed to throwing `AS_PROTO_RESULT_FAIL_BIN_NAME`. If you do a get, the error is thrown correctly.

**Comment by jhecking** [comment] 2016-02-23 06:54
@rschmukler, the client should return a `AEROSPIKE_ERR_PARAM` error (code: -2) when you try to put a record with a bin name exceeding the limit:

````
$ cat long_bin_test.js
as = require('aerospike')
client = as.client().connect(function () {})

client.put({ns: 'test', set: 'test', key: 'long_bin'}, {this_bin_name_is_too_long: 1, this_is_ok: 2}, function (err) { console.log(err) })
client.get({ns: 'test', set: 'test', key: 'long_bin'}, function (err, record) { console.log(err, record) })

$ node long_record_bin_test.js
Feb 23 2016 06:51:17 UTC: ERROR(28600) [conversions.cc:1023] [recordbins_from_jsobject] - Valid length for a bin name is 14. Bin name length exceeded
Feb 23 2016 06:51:17 UTC: ERROR(28600) [put.cc:120] [prepare] - Parsing as_record(C structure) from record object failed
{ code: -2,
  message: 'AEROSPIKE_ERR_PARAM',
  func: '',
  file: '../src/main/client/put.cc',
  line: 121 }
{ code: 2,
  message: 'AEROSPIKE_ERR_RECORD_NOT_FOUND',
  func: 'as_command_parse_result',
  file: 'src/main/aerospike/as_command.c',
  line: 1071 } {}
```

Am I misunderstanding the issue you are describing?

**Comment by jhecking** [comment] 2016-04-01 01:53
Tested this as well on 2.0.0-alpha.1 and am still not able to reproduce:

```
$ node long_record_bin_test.js
Apr 01 2016 01:50:38 UTC: ERROR(26035) [conversions.cc:1056] [recordbins_from_jsobject] - Valid length for a bin name is 14. Bin name length exceeded
{ [AerospikeError: Record object invalid]
  name: 'AerospikeError',
  message: 'Record object invalid',
  code: -2,
  func: undefined,
  file: undefined,
  line: undefined }
{ [AerospikeError: AEROSPIKE_ERR_RECORD_NOT_FOUND]
  name: 'AerospikeError',
  message: 'AEROSPIKE_ERR_RECORD_NOT_FOUND',
  code: 2,
  func: 'as_event_command_parse_result',
  file: 'src/main/aerospike/as_event.c',
  line: 614 } undefined
````

Closing this issue for now, @rschmukler, feel free to reopen with additional information on how to reproduce.

**Closed by jhecking** 2016-04-01 01:53 UTC
