### ISSUE TITLE
 Aerospike.key is not a constructor

### ISSUE THREAD

**Issue by Vidz51** [aerospike/aerospike-client-nodejs#368] opened 2020-05-26 10:58 UTC
Hi 
I am  doing a get operation in aerospike. When I make a key object. I get the below error
const Aerospike = require("aerospike");
client = await Aerospike.connect(config, (error) => {
		if (error) {
			logger.error("Connection to Aerospike cluster failed!");
		} else {
			logger.info("Connection to Aerospike cluster succeeded!");
		}
	});

const Key = new Aerospike.Key(aerospikeConf.namespace, aerospikeConf.set, cacheKey);

const record = await client.get(key);
TypeError: Aerospike.key is not a constructor

**Comment by jhecking** [comment] 2020-05-27 17:59
```
const Key = new Aerospike.Key(aerospikeConf.namespace, aerospikeConf.set, cacheKey);

const record = await client.get(key);
```

You are assigning to `Key` (with capital "K"), but then reference a different variable `key` (with lowercase "k"). The might just be a typo in your simplified example. But can you please double check and maybe post a more complete example of your actual code?

**Comment by Vidz51** [comment] 2020-05-28 20:15
Hi

Thanks!
One more question, right now I have a really big key, I want to hash it and
store the hash in aerospike cache.

Is that ok? Or keys are already hashed.

Regards
Vidushi

**Comment by jhecking** [comment] 2020-05-29 01:45
Quoting from the docs on [Keys and Digests](https://www.aerospike.com/docs/architecture/data-model.html#keys-and-digests):

> When a key is sent to the database, it and its optional set information are hashed into a 160-bit digest, which is used to address that record for all operations. So, you use the key in your application, while the digest is used for addressing the record in the database.

So yes, the key is already hashed. By default, only that hashed digest is sent to the server. However, this can be controlled via the [`key` policy value](https://www.aerospike.com/apidocs/nodejs/module-aerospike_policy.html#.key), e.g. via the [global policies in the client config](https://www.aerospike.com/apidocs/nodejs/Config.html#policies).

One scenario where it can be required to send the full key to the server, is when you are planning to run scans or queries on your data, and you need the results to include the full record key. But that depends on your use case.

It seems this issue is resolved, so I'm going to close it. Feel free to reopen if I've misunderstood and the issue is not actually resolved yet.

**Closed by jhecking** 2020-05-29 01:45 UTC
