### ISSUE TITLE
uv assertion during concurent queries

### ISSUE THREAD

**Issue by maxvgi** [aerospike/aerospike-client-nodejs#49] opened 2015-04-15 16:12 UTC
I am running queries with secondary index filter from node process.

Single query always succeedes. But if I run several (2 or more) queries in parallel, in the most cases node.js process terminates with the following message:
```
node: ../deps/uv/src/unix/core.c:209: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.
```

It seemes that the assertion failes immediately before the 'end' event of one of the queries because of some racing conditions.

Example code to reproduce the situation:
```
var run_query=function(set_name,from,to) {
    var statement = {
        filters: [aerospike.filter.range("bin", from, to)]
    };

    var scan = client.query("ns", set_name, statement);

    var recordCount = 0;

    console.error('execute', set_name);
    var stream = scan.execute();

    stream.on('data', function (record) {
        recordCount++;
        console.error('     DATA', set_name, recordCount);
    });

    stream.on('error', function (e) {
        console.error('ERR', set_name, e);
    });

    stream.on('end', function () {
        console.error('END', set_name);
    });
};

run_query('1',0,1000);
run_query('2',0,1000);
run_query('3',0,1000);
run_query('4',0,1000);
```

Output is the following:
```
execute 1
execute 2
execute 3
execute 4
    DATA 2 1
    DATA 2 2
    DATA 2 3
    DATA 2 4
    DATA 2 5
  .... (all data from set 2)
END 2
    DATA 1 1
    DATA 1 2
    DATA 1 3
    DATA 1 4
    DATA 1 5
  .... (all data from set 1)
node: ../deps/uv/src/unix/core.c:209: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.
```

No 'error' events are emitted, all namespaces, sets and indexes do exist.

Node.js v0.12.2
Aerospike client 1.0.36
Aerospike server 3.5.8-1, Debian 7

**Comment by GayathriKaliyamoorthy** [comment] 2015-04-16 06:51
Thanks for reporting this issue.
I am looking into the issue, will update you after we resolve this issue.

**Comment by arch1t3ct** [comment] 2015-04-20 05:05
I can confirm this too. Under high concurrent requests for our http server we get the same errors. Node v0.10.37, Aerospike client 1.0.35, server 0.3.4.0, Debian 7.

**Comment by GayathriKaliyamoorthy** [comment] 2015-04-27 06:09
Hi @maxvgi 

We found the bug. The fix will be available in the official npm repo  within this week.

Thanks

**Comment by GayathriKaliyamoorthy** [comment] 2015-04-30 19:21
Hi @maxvgi 

We made a release to NPM with the fix for this. Please let us know if your issue is solved, so that we can close the issue.

Thanks

**Comment by ryanwitt** [comment] 2015-05-01 21:59
Looks like 1.0.38 fixes this for me.

**Comment by GayathriKaliyamoorthy** [comment] 2015-05-04 07:00
@ryanwitt 
Thanks for the confirmation.

**Closed by GayathriKaliyamoorthy** 2015-05-04 07:00 UTC

**Comment by maxvgi** [comment] 2015-05-08 16:32
@GayathriKaliyamoorthy yes, thank you
