### ISSUE TITLE
infoAll not querying all nodes

### ISSUE THREAD

**Issue by sempi** [aerospike/aerospike-client-nodejs#192] opened 2017-04-23 04:48 UTC
When calling infoAll with a timeout of 5 seconds (timeout=5000) it's common for only a subset of the cluster to respond when the cluster is more than 100ms away from the client (physical distance). Typically it's the same node that's omitted from the overall response. From that observation, it's very likely that the timeout is not honored for the last (perhaps only the first) node to respond.

When we query each node individually by first requesting the cluster list from one then query all for their statistics then we are able to confirm that the cluster works properly despite infoAll only returning a subset.

This might be a bug in the aerospike client depending on how this is implemented passed the node.js interface.

**Comment by jhecking** [comment] 2017-04-24 08:00
`infoAll` queries all nodes sequentially and the timeout applies to the entire `infoAll` call, not to each individual info query for each node.

**Comment by sempi** [comment] 2017-04-24 13:26
It's not working. We got month of operational experience to back it up with
different client and server versions. Often we get only 2 of 3 node
responding. It's sometimes permanent for that client. Other clients,
sometimes in the same location and sometimes other, do not have that issue.
Their infoAll contains all 3 nodes of the cluster. Out of 6 clusters and 12
clients all connecting to each cluster. 2-3 connections will have that
issue.

We implemented our own version of infoAll that solves the issue. First,
list neighbors of one node then query each individually. That seems to
reliably return all data.

**Comment by sempi** [comment] 2017-04-27 16:04
Igoring the infoAll not returning all nodes in the cluster might produce partial scan results thereafter. Is that possible?

**Comment by sempi** [comment] 2017-04-27 16:25
Steps.

1. Insert a record in a cluster
2. Have many clients connect from locations physically >50 ms away with fiber.
3. Run query with a filter.

Expected result: The record always appears in the result

Actual result: Some of the clients will miss results

Second problem

1. Have many clients connect from locations physically >50 ms away with fiber.
2. infoAll

Expected result: All nods respond

Actually result: Only a subset of the nodes respond and result is completed before any timeout, e..g ~100ms with a 5s timeout.

Same setup
Querying one node about its neighbors and then info each node directly produces expected results.
However, subsequent query are now not returning all data on some of those nodes.

**Comment by sempi** [comment] 2017-04-27 16:32
In the second problem (as in the first), it affects about 1 out of 10 clients. So it's not happening to each client all the time. But when it happens, it never goes away for that machine unless a server node is stopped and restarted after a minute or so.

**Comment by sempi** [comment] 2017-04-27 16:40
@jhecking I'm 100% at this point that there is a bug. 

I created the workaround for the infoAll to call info directly to each node and discover through querying the neighbors of one of them. Each of the server nodes sees all of the cluster nodes. However, data is missing from queries now since I ignore infoAll not return all cluster nodes.

The same cluster works fine for 9 out of 10 clients at the same time that 1 out of 10 has issues seeing all nodes. Sometimes those clients are next to each other, i.e. exactly the same distance from the cluster.

This is now using 2.5.1 and the problem dates back to November or so. It started when we upgraded to the server release around that time. You closed a similar issue before but there was never a fix provided on the server either.

**Comment by wchu-citrusleaf** [comment] 2017-04-27 19:59
Thanks for all the detailed information. We've had local discussions and now have a very good candidate for root cause.

The issue is likely in the C client cluster-tend part, when it's trying to query a new neighboring node. When this call times out, the candidate node does not get added on the client side. Further more, it is subsequently not discovered again due to a peer-generation check optimization that was put in server 3.10.0.

Having a missing node on the client list also explain partial responses from scan and query requests.

An immediate work around to try is to increase the Config.connTimeoutMs (default is 1000) to minimize the likelihood of timeout. 

We are also working on a C client level fix. We can also make the C client fix available to you as a dev build to try out if you like.

Thans.

**Comment by sempi** [comment] 2017-04-27 20:04
Yes, is it possible to have the node.js client use that build somehow? Then
we would able to test it in our system.

**Comment by jhecking** [comment] 2017-05-25 02:49
@sempi, I just released Aerospike Node.js Client [v2.6](https://github.com/aerospike/aerospike-client-nodejs/releases/v2.6.0), which includes the cluster-tend fix (per C client release 4.1.6). Please give it a try.

I will go ahead and close this issue but feel free to re-open or file a new ticket if you are still having problems.

**Closed by jhecking** 2017-05-25 02:49 UTC
