### ISSUE TITLE
"Freeze" node.js process on client.close(false)

### ISSUE THREAD

**Issue by sempi** [aerospike/aerospike-client-nodejs#147] opened 2016-10-03 14:11 UTC
We observed freezing of the node.js process when invoking client.stop(false). The node.js "freezing" is quite fatal and results in the process becoming unresponsive to incoming network connections (and probably internally as well).

Perhaps this is a pre-condition for the issue to manifest. The only time we ever call client.stop(false) is just after we detect some issues with a client, e.g. a node was removed from the cluster of 3. Then we reconnect.

Not calling client.stop(false) avoids the "freezing" but obviously leaks the connection associated with the client.

**Comment by jhecking** [comment] 2016-10-04 02:32
Can you elaborate a bit more on the conditions under which you call `client.stop(false)`? How do you for example detect if a node was removed from the cluster?

**Comment by sempi** [comment] 2016-10-04 02:40
We call client.stop(false) after we detect errors using that client that is connected to a cluster. Then we create a new client and use start which will only succeed once the cluster is ok again. I guess its possible that it "blows" up on the subsequent client.start(...).

I was able to simulate this by stopping an aerospike node on the server in a cluster of 2 nodes which resulted in timeouts on the client and then triggered to stop()-create new client-start() repair protocol.

**Comment by sempi** [comment] 2016-10-04 02:43
If we don't call stop() but just create a new client and start() then it works fine but we leak connections to the server.

**Comment by jhecking** [comment] 2016-10-05 07:18
I have been trying to reproduce the issue with a simple script that I have uploaded as a [Gist](https://gist.github.com/a13e7be737e00848593e8a70ecee97ec). The script just runs random put/get requests in a fix interval; when an error occurs the client connection is closed an a new connection is opened. I ran the script against a cluster of two nodes and then stopped one of the two nodes. I get the expected error but then the client is able to reconnect without issues:

```
$ node reconnect.js true
[as_cluster.c:262][as_cluster_add_nodes_copy] Add node BB9EB63B2005452 192.168.33.10:3000
[as_cluster.c:262][as_cluster_add_nodes_copy] Add node C1DEB63B2005452 192.168.33.10:3100
[as_node.c:486][as_node_process_response] Node BB9EB63B2005452 peers generation changed: 15
[as_node.c:493][as_node_process_response] Node BB9EB63B2005452 partition generation changed: 14285
[as_node.c:486][as_node_process_response] Node C1DEB63B2005452 peers generation changed: 3
[as_node.c:493][as_node_process_response] Node C1DEB63B2005452 partition generation changed: 2036
[as_cluster.c:850][as_cluster_add_seeds] Add seed 192.168.33.10:3000
[as_cluster.c:850][as_cluster_add_seeds] Add seed 192.168.33.10:3100
[as_cluster.c:200][as_seeds_add] Add seed 192.168.33.10:3000:3000
[as_cluster.c:200][as_seeds_add] Add seed 192.168.33.10:3100:3100
.
.
.
.
[as_cluster.c:697][as_cluster_tend] Node C1DEB63B2005452 refresh failed: AEROSPIKE_ERR_CONNECTION Bad file descriptor
.
[as_event.c:384][as_event_get_connection] Invalid async socket from pool: -1
error writing record { AerospikeError: Failed to connect: C1DEB63B2005452 192.168.33.10:3100
    at Function.AerospikeError.fromASError (/Users/jhecking/aerospike/citrusleaf/aerospike-client-nodejs/lib/aerospike_error.js:113:10)
    at Client.DefaultCallbackHandler [as callbackHandler] (/Users/jhecking/aerospike/citrusleaf/aerospike-client-nodejs/lib/client.js:71:72)
    at putCb (/Users/jhecking/aerospike/citrusleaf/aerospike-client-nodejs/lib/client.js:1326:10)
  name: 'AerospikeError',
  message: 'Failed to connect: C1DEB63B2005452 192.168.33.10:3100',
  code: -6,
  func: 'as_uv_connected',
  file: 'src/main/aerospike/as_event_uv.c',
  line: 551 }
attempting to reconnect client - closing connection ...
... reconnecting ...
[as_cluster.c:372][as_cluster_seed_nodes] Failed to connect to seed 192.168.33.10:3100. AEROSPIKE_ERR_CONNECTION Socket write error: 32
[as_cluster.c:262][as_cluster_add_nodes_copy] Add node BB9EB63B2005452 192.168.33.10:3000
[as_node.c:486][as_node_process_response] Node BB9EB63B2005452 peers generation changed: 15
[as_node.c:493][as_node_process_response] Node BB9EB63B2005452 partition generation changed: 14285
[as_peers.c:185][as_peers_validate_node] Failed to connect to peer 192.168.33.10:3100. AEROSPIKE_ERR_CONNECTION Socket write error: 32
[as_cluster.c:850][as_cluster_add_seeds] Add seed 192.168.33.10:3000
[as_cluster.c:850][as_cluster_add_seeds] Add seed 192.168.33.10:3100
[as_cluster.c:200][as_seeds_add] Add seed 192.168.33.10:3000:3000
... done!
.
.
[as_node.c:486][as_node_process_response] Node BB9EB63B2005452 peers generation changed: 16
[as_node.c:493][as_node_process_response] Node BB9EB63B2005452 partition generation changed: 14286
.
.
```

But stepping back for a moment, why do you need to close and reconnect the client in the first place? The client will automatically detect if the cluster configuration changes, e.g. if a node leaves or joins the cluster, and will adapt accordingly.

For example in the same test case as before, here is what happens when do not close/reconnect and do nothing instead:

```
$ node reconnect.js false
[as_cluster.c:262][as_cluster_add_nodes_copy] Add node BB9EB63B2005452 192.168.33.10:3000
[as_cluster.c:262][as_cluster_add_nodes_copy] Add node C1DEB63B2005452 192.168.33.10:3100
[as_node.c:486][as_node_process_response] Node BB9EB63B2005452 peers generation changed: 17
[as_node.c:493][as_node_process_response] Node BB9EB63B2005452 partition generation changed: 16322
[as_node.c:486][as_node_process_response] Node C1DEB63B2005452 peers generation changed: 3
[as_node.c:493][as_node_process_response] Node C1DEB63B2005452 partition generation changed: 2036
[as_cluster.c:850][as_cluster_add_seeds] Add seed 192.168.33.10:3000
[as_cluster.c:850][as_cluster_add_seeds] Add seed 192.168.33.10:3100
[as_cluster.c:200][as_seeds_add] Add seed 192.168.33.10:3000:3000
[as_cluster.c:200][as_seeds_add] Add seed 192.168.33.10:3100:3100
.
.
.
[as_cluster.c:697][as_cluster_tend] Node C1DEB63B2005452 refresh failed: AEROSPIKE_ERR_CONNECTION Bad file descriptor
.
[as_event.c:384][as_event_get_connection] Invalid async socket from pool: -1
error writing record { AerospikeError: Failed to connect: C1DEB63B2005452 192.168.33.10:3100
    at Function.AerospikeError.fromASError (/Users/jhecking/aerospike/citrusleaf/aerospike-client-nodejs/lib/aerospike_error.js:113:10)
    at Client.DefaultCallbackHandler [as callbackHandler] (/Users/jhecking/aerospike/citrusleaf/aerospike-client-nodejs/lib/client.js:71:72)
    at putCb (/Users/jhecking/aerospike/citrusleaf/aerospike-client-nodejs/lib/client.js:1326:10)
  name: 'AerospikeError',
  message: 'Failed to connect: C1DEB63B2005452 192.168.33.10:3100',
  code: -6,
  func: 'as_uv_connected',
  file: 'src/main/aerospike/as_event_uv.c',
  line: 551 }
[as_cluster.c:697][as_cluster_tend] Node C1DEB63B2005452 refresh failed: AEROSPIKE_ERR_CONNECTION Socket write error: 32
.
error writing record { AerospikeError: Failed to connect: C1DEB63B2005452 192.168.33.10:3100
    at Function.AerospikeError.fromASError (/Users/jhecking/aerospike/citrusleaf/aerospike-client-nodejs/lib/aerospike_error.js:113:10)
    at Client.DefaultCallbackHandler [as callbackHandler] (/Users/jhecking/aerospike/citrusleaf/aerospike-client-nodejs/lib/client.js:71:72)
    at putCb (/Users/jhecking/aerospike/citrusleaf/aerospike-client-nodejs/lib/client.js:1326:10)
  name: 'AerospikeError',
  message: 'Failed to connect: C1DEB63B2005452 192.168.33.10:3100',
  code: -6,
  func: 'as_uv_connected',
  file: 'src/main/aerospike/as_event_uv.c',
  line: 551 }
[as_node.c:486][as_node_process_response] Node BB9EB63B2005452 peers generation changed: 18
[as_node.c:493][as_node_process_response] Node BB9EB63B2005452 partition generation changed: 16323
[as_cluster.c:697][as_cluster_tend] Node C1DEB63B2005452 refresh failed: AEROSPIKE_ERR_CONNECTION Socket write error: 32
[as_cluster.c:500][as_cluster_remove_nodes_copy] Remove node C1DEB63B2005452 192.168.33.10:3100
.
.
.
```

As you can see the client automatically removes the node that left the cluster but afterwards continues to successfully send put/get requests to the remaining cluster node(s).

**Comment by sempi** [comment] 2016-10-05 12:17
So this may or may not be true with the 2.X client.

The reason we create a new one once we get error is because with 1.X, if we had connection to multiple clusters, then failure/timeouts of one cluster caused clients of other clusters to "dry up". It looked like the connection pool was shared and as soon as enough connection were pending to the faulty clusters, then the clients to other cluster would not have resources to use and therefor all clusters started getting errors. So we wanted to avoid any requests to go to that client. It was just the reasonable thing to close the client. Then to bring the client back online, we connect a new one which provides a callback once the connection is established which only happens after the cluster is stable.

Therefore we implemented the workflow to create a new client once we see errors to avoid locking up our app.

How would you recommend reliably testing if a client is back operational that is requests will not result in a timeout due to cluster resizing/failure of node or network timeouts?

What node version are you using? We used 4.4.7.

Also, our errors are typically coming from a scan operation.

**Comment by sempi** [comment] 2016-10-05 12:35
Just to make it clear. In 1.x, if the client started getting timeouts and we were keep making requests (at high volume) then eventually it would put that client and all other clients to other clusters into a mode were all requests fail and it would not recover.

**Comment by jhecking** [comment] 2016-10-05 14:34
Despite the asynchronous, callback-based API of the v1 client, the underlying I/O was synchronous. That means all of the communication with the Aerospike cluster actually happened using libuv's worker thread pool. By default, the worker pool size is limited to only 4 threads. If you were running into timeouts at a high volume then I suspect what happened is that all of the worker threads were busy waiting for timeouts and that's why even requests to other clusters would be affected.

The v2 client uses true asynchronous I/O for most single key queries as well as nearly all scan/query operations. These operations do no longer user libuv's worker pool. Therefore a similar issue cannot occur with the v2 client.

Are most of your operations scan operations or just a few that are disproportionally the cause of the errors?

**Comment by sempi** [comment] 2016-10-06 03:44
The cause of errors are typically the scan operations. I assume the reason for that is they are going to many nodes and therefore will be delayed if a recovery is in progress which then results in timeouts.

Under the heavy load scenario, it will pick up on simple fetch/store/increment/decrement operations. The total failure scenario in v1 was in "overloading" on those operations.

**Comment by jhecking** [comment] 2016-10-06 03:55
That sounds plausible. But is should no longer be an issue with v2. I would recommend, that with the v2 client you should not close the connection and reconnect when you are getting timeout errors and instead rely on the client to update the cluster status as necessary.

**Comment by sempi** [comment] 2016-10-06 05:08
Ok.

How can I test when the client is ready again? Is there a call that I can make that has the same effect as connect(), i.e. it tells me when the client is successfully connected to the cluster and can make requests without failures.

**Comment by jhecking** [comment] 2016-10-06 07:58
There is no such test at the moment. What happens after connect() is that the client waits for at least two consecutive cluster tend intervals until the cluster size remains stable. But is there is currently no way to perform a similar check once the client is connected.

**Comment by sempi** [comment] 2016-10-06 14:07
I replaced it with infoAll('statistics',...) and make sure the cluster size is the same on all nodes.

Is a cluster tend basically that twice in a row while making sure the size is the same in each pass?

**Comment by jhecking** [comment] 2017-04-05 10:37
Sorry for never getting back to you on this.

Cluster tend is a continuous background process during which the client queries each node to determine it's health status and to update the client's copy of the cluster partition map, which is used to determine which node is the master for any given record. During normal operation this tend process is performed about once per second. (This can be configured.)

During startup, the client performs this tend process continuously until the cluster size has stabilized, i.e. until no more new nodes can be found.

Are you ok to close this issue now?

**Comment by sempi** [comment] 2017-04-05 15:01
Hi Jan,

With server 3.12.0 and client 2.4.4, there is still issues with the tend
process. Many times it takes >15 seconds to find all nodes in the cluster.
This seems to happen most frequently if the cluster is >80ms away from the
client. It almost never happens when the cluster is <10ms away from the
client.

s_

**Comment by jhecking** [comment] 2017-04-06 00:08
How big is the cluster? With the Node.js/C client the tend process is still sequential, i.e. the client queries the cluster nodes one after another. We are considering to parallelize this process to reduce the duration of the tend process especially for larger clusters but have not made a decision on this yet.

**Comment by sempi** [comment] 2017-04-06 00:10
It happens with 2 and 3 node clusters.

**Closed** 2020-03-16 07:22 UTC
