### ISSUE TITLE
node js in profiling mode with --prof parameter

### ISSUE THREAD

**Issue by dsivolap** [aerospike/aerospike-client-nodejs#100] opened 2016-01-11 11:08 UTC
if i use --prof parameter to profiling my code, for example: node --prof app.js i got error from aerospike client module: ERROR(12629) [connect.cc:69] [Connect] - Connecting to Cluster Failed {"code":-1,"message":"Failed to seed cluster","func":"as_cluster_seed_nodes","file":"src/main/aerospike/as_clust er.c","line":319}

if start without profiling mode, all ok. Client version 1.0.54

**Comment by jhecking** [comment] 2016-01-11 15:04
The problem is caused by the timer signals generated by the V8 profiler to collect samples. These `SIGPROF` interrupts cause some I/O operations in the client to return `EINTR` errors which are currently not handled correctly. The client should attempt to resume the I/O operations but returns an error to the application instead.

This needs to be fixed in the aerospike C client library which is used by the aerospike Node.js client internally. There is unfortunately no work-around available at the moment. I'll keep you posted once I know when we will be able to release a fixed client version.

**Comment by jhecking** [comment] 2016-01-15 11:09
This is fixed in `aerospike@1.0.55`.

**Closed by jhecking** 2016-01-15 11:09 UTC
Labels: bug
