### ISSUE TITLE
npm install not working on Alpine Linux

### ISSUE THREAD

**Issue by ApsOps** [aerospike/aerospike-client-nodejs#125] opened 2016-04-30 12:07 UTC
Running `npm install aerospike` on Alpine Linux fails with following error:
```
# npm install aerospike
\
> aerospike@1.0.57 install /app/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/app/node_modules/aerospike/build'
  TOUCH binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
/bin/sh: scripts/aerospike-client-c.sh: not found
aerospike-client-c.target.mk:16: recipe for target 'binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate' failed
make: *** [binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate] Error 127
rm binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
make: Leaving directory '/app/node_modules/aerospike/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.19-boot2docker
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/aerospike
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 4.1.19-boot2docker
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "aerospike"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! aerospike@1.0.57 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aerospike@1.0.57 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aerospike
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
```

This seems weird - `/bin/sh: scripts/aerospike-client-c.sh: not found` since it's supposed to come from aerospike repo.

How can I debug this further?

**Comment by jhecking** [comment] 2016-04-30 12:18
Duplicate of #117.

**Closed by jhecking** 2016-04-30 12:18 UTC
Labels: duplicate
