### ISSUE TITLE
infoAll() returns partial results with server v3.10.1

### ISSUE THREAD

**Issue by sempi** [aerospike/aerospike-client-nodejs#157] opened 2016-11-28 07:51 UTC
server C-3.10.1
client 2.4.3

It appears infoAll('statistics', ...) does no longer return one record for each cluster member.

**Comment by jhecking** [comment] 2016-11-28 18:29
Sorry, not able to reproduce. With an admittedly small cluster size of 3 nodes I'm consistently getting the expected 3 results when querying stats using `infoAll`:

    > client.infoAll('statistics', (_err, results) => { console.log(results.map((r) => r.host.node_id)) })
    > [ 'BB9EB63B2005452', 'C1DEB63B2005452', 'C81EB63B2005452' ]

What are you getting when you call `infoAll`? A single result? A (random?) subset of results? Something else entirely?

**Comment by sempi** [comment] 2016-11-29 00:14
Here is an example response: It contains just one record. Though the record itself says the cluster size is 2.

We have code that asserts that the number of records and cluster_size matches on startup so that this was never ever an issue until we upgraded to C-3.10.1.

[{"host":{"node_id":"BB90700F00A0142"},"info":"statistics\tcluster_size=2;cluster_key=SOMETHINGSECRET;cluster_integrity=true;uptime=260770;system_free_mem_pct=82;system_swapping=false;heap_allocated_kbytes=6760679;heap_active_kbytes=6771260;heap_mapped_kbytes=6995968;heap_efficiency_pct=97;objects=70124;sub_objects=0;tombstones=0;tsvc_queue=0;info_queue=0;delete_queue=0;rw_in_progress=0;proxy_in_progress=0;tree_gc_queue=0;client_connections=17;heartbeat_connections=1;fabric_connections=27;heartbeat_received_self=0;heartbeat_received_foreign=1737519;reaped_fds=11;info_complete=799299;proxy_retry=0;demarshal_error=0;early_tsvc_client_error=0;early_tsvc_batch_sub_error=0;early_tsvc_udf_sub_error=0;batch_index_initiate=0;batch_index_queue=0:0,0:0,0:0,0:0;batch_index_complete=0;batch_index_error=0;batch_index_timeout=0;batch_index_unused_buffers=0;batch_index_huge_buffers=0;batch_index_created_buffers=0;batch_index_destroyed_buffers=0;batch_initiate=0;batch_queue=0;batch_error=0;batch_timeout=0;scans_active=0;query_short_running=0;query_long_running=0;sindex_ucgarbage_found=0;sindex_gc_locktimedout=0;sindex_gc_inactivity_dur=257276756;sindex_gc_activity_dur=16245;sindex_gc_list_creation_time=15082;sindex_gc_list_deletion_time=96;sindex_gc_objects_validated=5777251;sindex_gc_garbage_found=6;sindex_gc_garbage_cleaned=6;paxos_principal=BB90700F00A0142;migrate_allowed=true;migrate_partitions_remaining=0;fabric_msgs_sent=1244149;fabric_msgs_rcvd=1244136\n","error":{"code":0,"message":"","func":"","file":"","line":0}}]

Perhaps related. I upgraded several clusters to C-3.10.1 and am seeing weird behavior with queries where some queries only return partial results. Almost as if some clients don't query all the nodes.

**Comment by sempi** [comment] 2016-11-29 01:37
Also, I'm connecting to multiple clusters simultaneously. In this particular example, one of the cluster has only one node, the other has two. I can see the first cluster connecting successfully then the second one will only return one record (even though there are 2 nodes). I keep retrying by creating a new client and after several tries it sometimes succeeds.

When I connect to the cluster with 2 nodes first, then it works fine for the cluster with one node.

**Comment by jhecking** [comment] 2016-11-29 01:48
From what server version did you upgrade to 3.10.1? And did you upgrade the client at the same time or did this same scenario work previously with client v2.4.3?

If you are upgrading from a pre-3.10 server version, please be sure to follow the [Network Configuration Migration Guide for 3.10 Release](http://www.aerospike.com/docs/operations/upgrade/network_to_3_10).

**Comment by sempi** [comment] 2016-11-29 01:59
I upgraded from 3.9

`asadm -e info` looks good for all clusters.

Besides this issue, I saw queries not returning all data for some clients (others work fine at the same time).

**Comment by jhecking** [comment] 2016-11-29 02:22
It sounds like you haven't done any changes on the client side. Therefore I suspect that the issue might be related to the server side upgrade 3.9 -> 3.10.1. It could be that one or more of the server nodes  are not responding to the queries. If you are using the enterprise version, it would be best if you could open a ticket with our support team.

**Comment by wchu-citrusleaf** [comment] 2016-11-29 04:13
On the 3.10.1 node, were you able to do asinfo calls individually to each of the 2 nodes?
Was there anything in the server log that may indicate any abnormality? (for example warnings) Was this behavior persistent even after you restarted the node? Maybe snippet of the log? Thanks.

**Comment by sempi** [comment] 2016-11-29 07:27
Below all the warnings throughout the testing. There appears no correlation between warning logs and the observed issues. I did not try `asinfo` but I used `asadm -e info` and there was nothing different from then to now when it's working. Each node showed all the other cluster members, the correct cluster size and cluster integrity with value "true".

Nov 29 2016 03:19:04 GMT: WARNING (cf:socket): (socket.c:760) Error while connecting FD 94: 111 (Connection refused)
Nov 29 2016 03:19:04 GMT: WARNING (cf:socket): (socket.c:819) Error while connecting socket to A.B.C.D:3002
Nov 29 2016 03:19:05 GMT: WARNING (cf:socket): (socket.c:760) Error while connecting FD 78: 111 (Connection refused)
Nov 29 2016 03:19:05 GMT: WARNING (cf:socket): (socket.c:819) Error while connecting socket to A.B.C.D:3002
Nov 29 2016 03:19:05 GMT: WARNING (cf:socket): (socket.c:760) Error while connecting FD 78: 111 (Connection refused)
Nov 29 2016 03:19:05 GMT: WARNING (cf:socket): (socket.c:819) Error while connecting socket to A.B.C.D:3002
Nov 29 2016 03:19:06 GMT: WARNING (cf:socket): (socket.c:760) Error while connecting FD 86: 111 (Connection refused)
Nov 29 2016 03:19:06 GMT: WARNING (cf:socket): (socket.c:819) Error while connecting socket to A.B.C.D:3002
Nov 29 2016 03:19:07 GMT: WARNING (cf:socket): (socket.c:760) Error while connecting FD 78: 111 (Connection refused)
Nov 29 2016 03:19:07 GMT: WARNING (cf:socket): (socket.c:819) Error while connecting socket to A.B.C.D:3002
Nov 29 2016 03:19:08 GMT: WARNING (hb): (hb.c:5236) Received message without associated channel.
Nov 29 2016 03:20:16 GMT: WARNING (as): (as.c:439) will not write PID file in new-style daemon mode
Nov 29 2016 03:20:16 GMT: WARNING (hb): (hb.c:7637) Ignoring adding self a-hostname-2:3002 as mesh seed 
Nov 29 2016 03:22:17 GMT: WARNING (cf:socket): (socket.c:760) Error while connecting FD 59: 111 (Connection refused)
Nov 29 2016 03:22:17 GMT: WARNING (cf:socket): (socket.c:819) Error while connecting socket to A.B.C.E:3002
Nov 29 2016 03:22:18 GMT: WARNING (cf:socket): (socket.c:760) Error while connecting FD 66: 111 (Connection refused)
Nov 29 2016 03:22:18 GMT: WARNING (cf:socket): (socket.c:819) Error while connecting socket to A.B.C.E:3002


With several clients connecting to different clusters, we observed the problem where infoAll('statistics', ) did not return not all records. However, there were always more combination of clients and clusters that worked fine. Maybe 5 out of 25 permutations would have this problem.

To get the software started, I disabled the infoAll check but then I also saw query() return partial results which roughly could have been matched up with the client<>cluster pairs that had issues with infoAll(..). 

For the clients that had issues with partial results. It sometimes helped to restart server nodes but sometimes the problems reappeared as new keys were added. This "missing results" problem was preformed only with a few keys so it's quite possible that it was just the odds of the keys falling on the same server node that could temporarily alleviate/mask the issue.

**Comment by sempi** [comment] 2016-11-29 07:36
Another observation, the client<>cluster pairs that had issues tended to be the ones with higher RTT of about 100-200ms (with no losses).

In increased the infoAll timeout to 5000 with no luck though.

**Comment by wchu-citrusleaf** [comment] 2016-11-29 08:13
100-200ms is terribly high. This probably is pointing to some network issue, where some of your server nodes are not directly reachable by the clients, and those requests may be proxied. 

See if you see any numbers in the proxy count.

Nov 29 2016 08:10:44 GMT: INFO (info): (ticker.c:551) {test} client: tsvc (0,0) proxy (0,0,0) read (1397,0,0,16026) write (17547,0,0) delete (0,0,0,0) udf (0,0,0) lang (0,0,0,0)

**Comment by sempi** [comment] 2016-11-29 18:00
It's not terribly high. It's what it takes with fiber from europe to us/asia.

Also, it has been working for over a year and it works fine with 3.10.0.3.

All log records have proxy (0,0,0).

But as I indicated above this is clearly a 3.10.1 regression.

**Comment by jhecking** [comment] 2017-01-12 09:55
Closing this as it doesn't seem to be a client issue and might be a server regression instead.

**Closed by jhecking** 2017-01-12 09:55 UTC
