### ISSUE TITLE
make the cline build on alpine linux (musl libc)

### ISSUE THREAD

**Issue by dmytroleonenko** [aerospike/aerospike-client-nodejs#117] opened 2016-03-31 13:43 UTC
Installed bash, python, alpine-sdk and clang on alpine linux docker image with nodejs and npm
~ # node -v
v5.9.1
~ # npm -v
3.8.3
with 
bash-4.3# cat /etc/issue
debian
bash-4.3# cat /etc/debian_version
7.0
I was able to build it with CC=/usr/bin/clang CXX=/usr/bin/clang++
but then ldd would result in 

> bash-4.3# ldd ./build/Release/aerospike.node
>   ldd (0x556f03bcb000)
>   libc.musl-x86_64.so.1 => ldd (0x556f03bcb000)
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object3GetEj: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v82V88MakeWeakEPPNS_8internal6ObjectEPvPFvRKNS_16WeakCallbackDataINS_5ValueEvEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object16SetInternalFieldEiNS_5LocalINS_5ValueEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v87Isolate17GetCurrentContextEv: symbol not found
> Error relocating ./build/Release/aerospike.node: __strndup: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object3SetENS_5LocalINS_5ValueEEES3_: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v816FunctionTemplate17PrototypeTemplateEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v88Template3SetENS_5LocalINS_4NameEEENS1_INS_4DataEEENS_17PropertyAttributeE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86String11NewFromUtf8EPNS_7IsolateEPKcNS_13NewStringTypeEi: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value9ToIntegerENS_5LocalINS_7ContextEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v814ObjectTemplate21SetInternalFieldCountEi: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object3GetENS_5LocalINS_5ValueEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Number3NewEPNS_7IsolateEd: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v87Isolate14ThrowExceptionENS_5LocalINS_5ValueEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: RAND_bytes: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN4node12MakeCallbackEPN2v87IsolateENS0_5LocalINS0_6ObjectEEENS3_INS0_8FunctionEEEiPNS3_INS0_5ValueEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object3SetEjNS_5LocalINS_5ValueEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object3HasENS_5LocalINS_5ValueEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN4node6Buffer6LengthEN2v85LocalINS1_6ObjectEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v82V812ToLocalEmptyEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value12BooleanValueEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v89Signature3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v88Function11NewInstanceEiPNS_5LocalINS_5ValueEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _Znwm: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value7IsArrayEv: symbol not found
> Error relocating ./build/Release/aerospike.node: uv_close: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v86Uint325ValueEv: symbol not found
> Error relocating ./build/Release/aerospike.node: node_module_register: symbol not found
> Error relocating ./build/Release/aerospike.node: SHA1: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN4node14FatalExceptionEPN2v87IsolateERKNS0_8TryCatchE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v88TryCatch9HasCaughtEv: symbol not found
> Error relocating ./build/Release/aerospike.node: uv_async_init: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v87Integer15NewFromUnsignedEPNS_7IsolateEj: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v814ObjectTemplate11SetAccessorENS_5LocalINS_4NameEEEPFvS3_RKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS3_NS1_IS5_EERKNS4_IvEEESB_NS_13AccessControlENS_17PropertyAttributeENS1_INS_17AccessorSignatureEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v82V89ClearWeakEPPNS_8internal6ObjectE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object18GetConstructorNameEv: symbol not found
> Error relocating ./build/Release/aerospike.node: RIPEMD160_Init: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object20SlowGetInternalFieldEi: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v811HandleScopeD2Ev: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPPNS1_6ObjectE: symbol not found
> Error relocating ./build/Release/aerospike.node: compressBound: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value8IsUint32Ev: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN4node6Buffer11HasInstanceEN2v85LocalINS1_5ValueEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v814ObjectTemplate11NewInstanceENS_5LocalINS_7ContextEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v811HandleScopeC1EPNS_7IsolateE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value9ToBooleanENS_5LocalINS_7ContextEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: RIPEMD160_Update: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v811HandleScope12CreateHandleEPNS_8internal7IsolateEPNS1_6ObjectE: symbol not found
> Error relocating ./build/Release/aerospike.node: RIPEMD160_Final: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value8IsObjectEv: symbol not found
> Error relocating ./build/Release/aerospike.node: uv_queue_work: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN4node6Buffer4CopyEPN2v87IsolateEPKcm: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v87Integer5ValueEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object3NewEPNS_7IsolateE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v88Function7SetNameENS_5LocalINS_6StringEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object38SlowGetAlignedPointerFromInternalFieldEi: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value12IntegerValueEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNSt8ios_base4InitC1Ev: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object32SetAlignedPointerInInternalFieldEiPv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v814ObjectTemplate3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v87Integer3NewEPNS_7IsolateEi: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi: symbol not found
> Error relocating ./build/Release/aerospike.node: uv_async_send: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v816FunctionTemplate16InstanceTemplateEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN4node6Buffer4DataEN2v85LocalINS1_6ObjectEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: pthread_rwlockattr_setkind_np: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value7IsInt32Ev: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v816FunctionTemplate12SetClassNameENS_5LocalINS_6StringEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object18InternalFieldCountEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value11NumberValueEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value10IsFunctionEv: symbol not found
> Error relocating ./build/Release/aerospike.node: RAND_seed: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86Object19GetOwnPropertyNamesEv: symbol not found
> Error relocating ./build/Release/aerospike.node: RIPEMD160: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v86Number5ValueEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v816FunctionTemplate11GetFunctionEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value8ToUint32ENS_5LocalINS_7ContextEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value9IsBooleanEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZdlPv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value8IsNumberEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value8ToStringENS_5LocalINS_7ContextEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v87Isolate10GetCurrentEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86String9Utf8ValueC1ENS_5LocalINS_5ValueEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v87Context6GlobalEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v89Exception5ErrorENS_5LocalINS_6StringEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v816FunctionTemplate11GetFunctionENS_5LocalINS_7ContextEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v87Boolean5ValueEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value8ToNumberENS_5LocalINS_7ContextEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value8ToObjectENS_5LocalINS_7ContextEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v88External3NewEPNS_7IsolateEPv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v820EscapableHandleScopeC1EPNS_7IsolateE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Array6LengthEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v88TryCatchC1EPNS_7IsolateE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Value7ToInt32ENS_5LocalINS_7ContextEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v86String6LengthEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v85Array3NewEPNS_7IsolateEi: symbol not found
> Error relocating ./build/Release/aerospike.node: uv_default_loop: symbol not found
> Error relocating ./build/Release/aerospike.node: compress2: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v88External5ValueEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v88TryCatchD1Ev: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v811HandleScopeD1Ev: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v811HandleScope12CreateHandleEPNS_8internal10HeapObjectEPNS1_6ObjectE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNK2v85Int325ValueEv: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v82V813DisposeGlobalEPPNS_8internal6ObjectE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN2v86String9Utf8ValueD1Ev: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZN4node6Buffer11HasInstanceEN2v85LocalINS1_6ObjectEEE: symbol not found
> Error relocating ./build/Release/aerospike.node: _ZNSt8ios_base4InitD1Ev: symbol not found

Can you please try to make it to work on alpine linux?

**Comment by dmytroleonenko** [comment] 2016-03-31 13:43
Docker image used: iron/node:dev

**Comment by jhecking** [comment] 2016-04-01 03:20
Alpine Linux is based on musl libc but the Aerospike C/C++ client library was build using glibc. That might be the root of the problem. I think the first step to resolve this would be to see whether the C client package can be compiled under Alpine Linux: https://github.com/aerospike/aerospike-client-c.

I won't be able to spend much time on this until after the release of the Aeorspike Node.js client v2.0.0. Maybe you can give it a try yourself and let me know how it goes?

**Comment by jhecking** [comment] 2016-04-01 03:21
Btw, are you trying to build v1.0.57 of the Aerospike Node.js client or the 2.0.0-alpha.1 pre-release? (In the latter case you would need to build the C client library with libuv support.)

**Comment by ApsOps** [comment] 2016-05-01 06:51
@jhecking Hi. Any update on this? I've been trying to install the node package as well as build C library. Both have been failing. Can you please give me some pointers here?

**Comment by jhecking** [comment] 2016-05-04 03:13
Hi @ApsOps, unfortunately I haven't been able to look into this yet. Generally, we aim to provide support for as many platforms as possible, but only provide pre-packaged and tested libraries for select platforms. In the case of the Aerospike Node.js SDK that means that you will have to compile the aerospike-client-c library from source yourself as we do not, currently, provide a pre-build package for Alpine Linux / musl libc.

You say you tried to build the C library and it failed. What error did you get while trying to compile it?

Are you using the iron.io Node.js microcontainer as well or do you use Alpine Linux for a different reason?

**Comment by ApsOps** [comment] 2016-05-04 07:09
@jhecking I tried with both the Iron node container and custom alpine linux container as well. Fails with following error(s). I'm not very familiar with compile process, so I might be missing something.
```
~/aerospike-client-c # make
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make -e -C /root/aerospike-client-c/modules/common libaerospike-common.a
make[1]: Entering directory '/root/aerospike-client-c/modules/common'
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
cc -Isrc/include -std=gnu99 -g -Wall -fPIC -O3 -fno-common -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -finline-functions -rdynamic -o target/Linux-/obj/common/aerospike/as_aerospike.o -c src/main/aerospike/as_aerospike.c
In file included from src/include/aerospike/as_aerospike.h:21:0,
                 from src/main/aerospike/as_aerospike.c:17:
src/include/citrusleaf/cf_clock.h:24:23: fatal error: bits/time.h: No such file or directory
compilation terminated.
Makefile:149: recipe for target 'target/Linux-/obj/common/aerospike/as_aerospike.o' failed
make[1]: *** [target/Linux-/obj/common/aerospike/as_aerospike.o] Error 1
make[1]: Leaving directory '/root/aerospike-client-c/modules/common'
project/modules.mk:36: recipe for target '/root/aerospike-client-c/modules/common/target/Linux-/lib/libaerospike-common.a' failed
make: *** [/root/aerospike-client-c/modules/common/target/Linux-/lib/libaerospike-common.a] Error 2
```

**Comment by felixsanz** [comment] 2016-08-01 20:29
any update on this? client libraries shouldn't be that much platform specific. Hell, i can't even install the client library in the machine i develop because it's Arch...

And in production i use alpine linux based images :(

> I won't be able to spend much time on this until after the release of the Aeorspike Node.js client v2.0.0. Maybe you can give it a try yourself and let me know how it goes?

It's now 2.2.0, how are things going?

**Comment by jhecking** [comment] 2016-08-02 02:22
Sorry, no update yet. The platform dependency is mostly due to the Aerospike C client library, which the Node.js client wraps. We only provide pre-compiled binaries for certain platforms. On other platforms you'll need to compile the C client library yourself.

**Comment by jhecking** [comment] 2016-10-11 03:22
The Aerospike C client library should now compile on Alpine Linux. We have made a few [minor changes](https://github.com/aerospike/aerospike-client-c/commit/74afe253144e1dd1ecb8402c34ede2bd9833e7df) to fix compatibility issues and these changes have now been merged back into master and are released in [Aerospike C Client v4.1.1](http://www.aerospike.com/download/client/c/notes.html#4.1.1).

Please note that while compile/execution works on Alpine Linux, we do not provide official Aerospike packages for this platform. You will have to compile the C library from source yourself and set the `PREFIX` and `AEROSPIKE_LUA_PATH` environment variables to the location of the compiled binaries and Lua system sources before you run `npm install aerospike`. Details can be found in the [README](https://github.com/aerospike/aerospike-client-nodejs#C-Client-Resolution).

**Comment by rma4ok** [comment] 2016-11-08 20:36
@jhecking I get C client compiled successfully but still get an error in node trying to `require` it

Could you provide a Dockerfile where you got it built or point to what I might be missing. 
Here is my Dockerfile
```Dockerfile
FROM mhart/alpine-node:6

WORKDIR /src
ADD . .

# Version of Lua we're building the image for.
ENV LUA_VERSION 5.1
ENV LUA_PACKAGE lua${LUA_VERSION}

# Update apk index.
RUN apk update

# Install packages necessary for Lua
RUN apk add --no-cache \
    build-base \
    bash git python linux-headers \
    libuv libuv-dev \
    openssl openssl-dev \
    ${LUA_PACKAGE} ${LUA_PACKAGE}-dev

ENV EVENT_LIB libuv
ENV USE_LUAJIT 1

# Build aerospike-client-c
RUN git clone https://github.com/aerospike/aerospike-client-c && \
    cd aerospike-client-c && \
    git checkout tags/4.1.1 && \
    git submodule update --init && \
    make


ENV USELUA 1
ENV PREFIX /src/aerospike-client-c/target/Linux-x86_64
ENV AEROSPIKE_LUA_PATH /src/aerospike-client-c/modules/lua-core/src
RUN npm install
```

**Comment by jhecking** [comment] 2016-11-10 09:16
@rma4ok, thanks for sharing your Dockerfile. I can reproduce the error with `require('aerospike')`:

    Error: Error relocating /src/node_modules/aerospike/build/Release/aerospike.node: compressBound: symbol not found

The `compressBound` function is part of the zlib library. I'm not sure why it is not getting linked as I can see that the `zlib` and `zlib-dev` packages are installed in your docker image. I'm wondering whether it has to do with the fact that `libz.a` gets installed in `/lib` rather than `/usr/lib` for some reason. But I need more time to investigate.

**Comment by rma4ok** [comment] 2016-11-10 15:18
@jhecking thank you a lot for taking a look at this. I think it would be great to have official aerospike-client-nodejs docker images for different platforms. Please let me know if I could help somehow

**Comment by jhecking** [comment] 2016-11-11 04:18
@rma4ok, I have updated the `bindings.gyp` file to explicitly link the zlib library in 8f56959e1851a907dcacedca8f285f033cfe4814. This change is included in the just released v2.4.3 package version. I can build and `require` the Aerospike library with your provided Dockerfile now. Please give it a try and let me know if you are still facing any issues.

**Closed by jhecking** 2016-11-11 04:18 UTC

**Comment by rma4ok** [comment] 2016-11-14 21:47
@jhecking thank you so much! You are the best!

**Comment by rma4ok** [comment] 2016-11-25 18:51
hello @jhecking I think it's not compiling with aerospike-client-c@4.1.2
but works fine for aerospike-client-c@4.1.1

**Comment by jhecking** [comment] 2016-11-28 19:49
> I think it's not compiling with aerospike-client-c@4.1.2

I've updated the Dockerfile to check out v4.1.2 instead of v4.1.1 and I don't see any compile errors.
I did however run into an issue installing the node module dependencies, specifically the `ansi-regex` module, during `npm install`. I haven't had time to investigate this further.

Regarding Lua: You'll have to set the `systemPath` in the `modlua` part of the client config:

    const Aerospike = require('aerospike')
    let config = {
      modlua: {
        systemPath: '/src/aerospike-client-c/modules/lua-core/src',
        userPath: '...' // path to your own Lua scripts
      }
    }
    Aerospike.connect(config, (err, client) => { 
      // ..
    })

The logic to automatically determine the correct system path needs some cleanup; but basically it doesn't use the `AEROSPIKE_LUA_PATH` at run-time and just checks for the existence of a few default locations:

https://github.com/aerospike/aerospike-client-nodejs/blob/master/src/main/config.cc#L273

**Comment by rma4ok** [comment] 2016-11-30 04:06
@jhecking thank you a lot! I am so grateful for your help! But I got rid of docker and run directly on Amazon Linux now.

Maybe setting `modlua: {systemPath: process.env.AEROSPIKE_LUA_PATH}` needs to be mention in README 
https://github.com/aerospike/aerospike-client-nodejs#custom-search-path

 About not compiling with `aerospike-client-c@4.1.2`. This is not important for me since I dropped docker.
My Dockerfile
```Dockerfile
FROM mhart/alpine-node:6

WORKDIR /src
ADD . .

# Version of Lua we're building the image for.
ENV LUA_VERSION 5.1
ENV LUA_PACKAGE lua${LUA_VERSION}

# Update apk index.
RUN apk update

# Install packages necessary for Lua
RUN apk add --no-cache \
    build-base \
    bash git python linux-headers \
    libuv libuv-dev \
    openssl openssl-dev \
    ${LUA_PACKAGE} ${LUA_PACKAGE}-dev

ENV EVENT_LIB libuv
ENV USE_LUAJIT 1

# Build aerospike-client-c
RUN git clone https://github.com/aerospike/aerospike-client-c && \
    cd aerospike-client-c && \
    git checkout tags/4.1.2 && \
    git submodule update --init && \
    make


ENV USELUA 1
ENV PREFIX /src/aerospike-client-c/target/Linux-x86_64
ENV AEROSPIKE_LUA_PATH /src/aerospike-client-c/modules/lua-core/src
RUN npm install aerospike
```
`docker pull mhart/alpine-node:6`
`docker build . -t test`
```coffeescript
CHECK
   [✓] /src/aerospike-client-c/target/Linux-x86_64/lib/libaerospike.a
   [✓] /src/aerospike-client-c/target/Linux-x86_64/include/aerospike/aerospike.h
   [✓] /src/aerospike-client-c/modules/lua-core/src/aerospike.lua

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
  CXX(target) Release/obj.target/aerospike/src/main/client.o
  CXX(target) Release/obj.target/aerospike/src/main/config.o
../src/main/config.cc: In function 'int config_from_jsobject(as_config*, v8::Local<v8::Object>, const LogInfo*)':
../src/main/config.cc:124:23: error: 'as_config_tls {aka struct as_config_tls_s}' has no member named 'protocol'
    strcpy(config->tls.protocol, protocol);
                       ^
aerospike.target.mk:156: recipe for target 'Release/obj.target/aerospike/src/main/config.o' failed
make: *** [Release/obj.target/aerospike/src/main/config.o] Error 1
```

**Comment by jhecking** [comment] 2016-12-01 01:09
> Maybe setting modlua: {systemPath: process.env.AEROSPIKE_LUA_PATH} needs to be mention in README

That's a good suggestion!

Re. compile error with `aerospike-client-c@4.1.2`: My bad, I thought you meant that v4.1.2 of the C client library does not compile on Alpine Linux. I will need to update the Node.js client to work with the latest C client release. The API for setting up TLS connections has changed in v4.1.2 compared to v4.1.1.

**Comment by felixsanz** [comment] 2017-01-11 21:13
I'm getting:

```
Error: Error loading shared library liblua.so.5.3: No such file or directory (needed by /usr/src/app/node_modules/aerospike/build/Release/aerospike.node)
```

Whats going on? :/

```
/ # find / -name "liblua*"
/usr/lib/lua5.3/liblua-5.3.so.0
/usr/lib/lua5.3/liblua-5.3.so.0.0.0
/usr/lib/lua5.3/liblua.so
/usr/lib/liblua-5.3.so.0
/usr/lib/liblua-5.3.so.0.0.0
/usr/lib/liblua.so.5.1.4
/usr/lib/liblua.so.5
/usr/lib/liblua.a
/usr/lib/liblua.so
```

**Comment by felixsanz** [comment] 2017-01-11 21:32
I manually linked it and now i'm getting `Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/aerospike/build/Release/aerospike.node)`

@jhecking is the client broken again on alpine?

**Comment by felixsanz** [comment] 2017-01-12 00:46
I'm gonna create a different message here because that doesn't seem to work at all.

I had to avoid using `USELUA` in order to get the nodejs client compile.
