### ISSUE TITLE
Query stream object pause is not a function. 

### ISSUE THREAD

**Issue by mbejda** [aerospike/aerospike-client-nodejs#95] opened 2015-10-29 01:16 UTC
Query stream object `pause()` is not a function.  
Example :

```
var scan = client.query("brand", "twitter", {
    concurrent: false,
    nobins: false,
});
var stream = scan.execute();

stream.on('data', function(record){
    console.log(record);
    var self = this;
self.pause(); //eerr
})

```

```
TypeError: self.pause is not a function
    at RecordStream.<anonymous> (/root/brandaffinity/classifier.js:37:14)
    at emitOne (events.js:77:13)
    at RecordStream.emit (events.js:169:7)
    at onResult (/root/brandaffinity/node_modules/aerospike/lib/aerospike.js:36:6)

```

**Comment by jhecking** [comment] 2017-04-05 09:23
Duplicate of #98.

**Closed by jhecking** 2017-04-05 09:23 UTC
