### ISSUE TITLE
Open handle after unsuccessful call to `.connect` keeps process running

### ISSUE THREAD

**Issue by rodrigoehlers** [aerospike/aerospike-client-nodejs#414] opened 2021-04-19 12:20 UTC
If a call to `.connect` fails, the module prevents the process from exiting gracefully and a call to `process.exit` is needed, which should not be the case.

**Comment by jhecking** [comment] 2021-04-20 04:09
Able to reproduce and you are right that this is not ideal.

Note that there is a fairly easy work-around in that you can call `client#close`  to release all open handles on the event loop, and will ensure that the process can shut down, e.g.

```
❯ cat test.js
const as = require('./')
as.connect({ hosts: '127.0.0.1:8888'}).then((client) => {
  client.close()
}).catch((error) => {
  console.error(error.message)
  if (error.client) error.client.close()
})

❯ node test.js && echo done
Apr 20 2021 04:09:15 UTC: WARN (94595) [as_cluster.c:331] [as_cluster_seed_node] - Failed to connect to seed 127.0.0.1 8888. AEROSPIKE_ERR_CONNECTION Socket write error: 32, 127.0.0.1:8888
Apr 20 2021 04:09:15 UTC: ERROR(94595) [command.cc:84] [ErrorCallback] - Client error in Connect command: Failed to connect [-10]
Failed to connect
done
```

(Without the `if (error.client) error.client.close()` the process will not terminate.)

**Comment by rodrigoehlers** [comment] 2021-04-20 05:37
Thanks for the quick confirmation of the issue and the suggested workaround. I've been trying to close the `client` from the same reference I called `.connect` on. I'll try to do so with the `client` reference inside the error and let you know what I find.

**Comment by jhecking** [comment] 2021-04-20 05:51
The referenced client object should be the same. Let me know if calling `client.close()` does not release all event loop handles either in your case. Btw, what client version are you using?

**Comment by rodrigoehlers** [comment] 2021-04-20 06:37
Definitely a difference. When calling `.close` on the same reference of the `client` I call the (then failing) `.connect` on, the process is kept alive. When I extract the `client` out of the error and call `.close` on that, the process does exit as expected.

I was using aerospike@3.16.4 when I wrote the above. I've since updated to aerospike@3.16.5 and can confirm that the behaviour is exactly the same.

I'd like to contribute to the project by either updating the documentation to hint at this issue and point to the indeed very simple workaround or update the code accordingly, however, I don't think I can do the latter since it most likely involves more than JavaScript/TypeScript work and I'm not too familiar with the other languages used in this project.

**Comment by jhecking** [comment] 2021-04-20 11:39
> Definitely a difference. When calling .close on the same reference of the client I call the (then failing) .connect on, the process is kept alive. When I extract the client out of the error and call .close on that, the process does exit as expected.

Hmm, that's interesting. I cannot reproduce that behavior using this simplified test case:

```
const as = require('aerospike')
const client = new as.Client({ hosts: '127.0.0.1:8888'})
client.connect().catch((error) => {
  console.error(error.message)
  client.close()
})
```

After closing the `client` instance the process terminates immediately in my case.

PRs to improve the documentation are always welcome! The `AerospikeError` docs already mention about the referenced client instance and the fact that it can be used to close the connection in the case of errors: https://www.aerospike.com/apidocs/nodejs/AerospikeError.html#client. (Generated from [lib/error.js](https://github.com/aerospike/aerospike-client-nodejs/blob/master/lib/error.js).) But probably this is not very discoverable and there might be other places where this information is missing?

**Comment by rodrigoehlers** [comment] 2021-04-20 11:43
Thanks for the quick response. I see the issue now... I was assigning my client as the return value of the `.connect` method, which obviously was undefined since it threw an error.

So the only _issue_ (if you can call it that) here is that when an error is thrown on `.connect` it should not need to be closed. However, this is absolutely arguable in both directions so I'll leave that up to you.

You are absolutely right about your docs, I simply didn't see that and assumed it wasn't there. Thanks for the help on this, this issue can be closed!

**Closed** 2021-04-27 15:15 UTC
